# usar base de datos mysql
version: '3.1'

services:
  db:
    image: mysql
    container_name: db_mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
