package biblioteca.view;

import javax.swing.JFrame;

/**
 *
 * @author Marco <marc.barrera@duocuc.cl>
 */
public class JFrameMainUI extends javax.swing.JFrame {

    JFrameUsuarioIniciarUI jfAuth = new JFrameUsuarioIniciarUI();
    JFrameLibroListarUI jfBookList = new JFrameLibroListarUI();
    JFrameLibroInsertarUI jfBookAdd = new JFrameLibroInsertarUI();
    
    /**
     * Creates new form JFrameMain
     */
    public JFrameMainUI() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);  
        setTitle("Biblioteca");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemBookAdd = new javax.swing.JMenuItem();
        jMenuItemBookList = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuOff = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(3, 43, 68));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        jMenu2.setText("Libros");

        jMenuItemBookAdd.setText("Agregar");
        jMenuItemBookAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBookAddActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemBookAdd);

        jMenuItemBookList.setText("Buscar");
        jMenuItemBookList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBookListActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemBookList);
        jMenu2.add(jSeparator1);

        jMenuBar1.add(jMenu2);

        jMenuOff.setText("Salir");
        jMenuOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuOffMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuOff);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBookListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBookListActionPerformed
        // TODO add your handling code here:
        this.jfBookList = new JFrameLibroListarUI();
        this.jfBookList.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemBookListActionPerformed

    private void jMenuOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuOffMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.jfAuth.setVisible(true);
        this.jfBookList.setVisible(false);
        this.jfBookAdd.setVisible(false);
    }//GEN-LAST:event_jMenuOffMouseClicked

    private void jMenuItemBookAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBookAddActionPerformed
        // TODO add your handling code here:
        this.jfBookAdd.setVisible(true);
    }//GEN-LAST:event_jMenuItemBookAddActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemBookAdd;
    private javax.swing.JMenuItem jMenuItemBookList;
    private javax.swing.JMenu jMenuOff;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
